### ISSUE TITLE
After deleting a log, it's description is not cleared in textinput

### ISSUE THREAD

**Issue by MilanJimi** [vacuumlabs/fine-tracker#176] opened 2019-06-27 10:50 UTC
1. Create an unsubmitted log
2. Delete the oldest unsubmitted log
3. Take a look at the bottom edit bar. It's not cleared

When no log is selected, time editor (`T`) clears itself as well as it pleases. Should be disabled instead

**Comment by domiin50** [comment] 2019-06-28 12:37
After deleting, the content of TextInput is changed to the new actually selected log.
When there is no work log selected and focus is on some input, it automatically switches to logging mode.
I see no issue, here. @mikx98 @jakuub ??

**Comment by mikx98** [comment] 2019-06-28 14:07
Agree with @domiin50, I tried it and imo it works as expected. The text and time input reflect the newly selected worklog. Closing, feel free to reopen if we misunderstood the issue.

**Comment by mikx98** [comment] 2019-06-28 14:49
:thinking: reopening, since I reproduced it. Removing the last (WIP) worklog really causes the description input to look weirdly - the text stays, together with overlapped `Description` placeholder

**Comment by domiin50** [comment] 2019-07-01 19:59
>  reopening, since I reproduced it. Removing the last (WIP) worklog really causes the description input to look weird - the text stays, together with overlapped `Description` placeholder

I am still unable to reproduce this by your description. Any detailed indications, please?

**Comment by mikx98** [comment] 2019-07-03 19:32
I am not able to reproduce it now, probably some other fix fixed this as well.

**Closed by mikx98** 2019-07-03 19:32 UTC
