### ISSUE TITLE
All times shifted one hour back

### ISSUE THREAD

**Issue by jozefhales** [vacuumlabs/fine-tracker#121] opened 2019-01-29 13:03 UTC
I've tried to use `fine-tracker` to log my day. When I submitted to `Jira` next day, everything was shifted by -1 hour, e.g., task lasting 8-9 am in `fine-tracker` appeared as 7-8 am task in `Jira`.

**Comment by jakuub** [comment] 2019-01-29 17:18
This is a duplicate of #93 , thank you for reporting :-)

**Closed by jakuub** 2019-01-29 17:18 UTC
