### ISSUE TITLE
Jira logs are created in UTC, not local timezone

### ISSUE THREAD

**Issue by MilanJimi** [vacuumlabs/fine-tracker#179] opened 2019-06-27 12:02 UTC
1. Create a log at 14:00 in Bratislava (CEST, which is UTC+2)
2. Save your log and open Jira
3. Jira logs this issue to 12:00

**Comment by mikx98** [comment] 2019-06-27 12:30
Duplicate of #93

**Closed by mikx98** 2019-06-27 12:30 UTC
